/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

/** sign(secretKey, msg, opt_random?) → signature 64 byte (XEdDSA) */
export declare function sign(secretKey: Uint8Array, msg: Uint8Array, optRandom?: Uint8Array | undefined | null): Buffer

/**
 * verify(publicKey, msg, signature) → bool (XEdDSA verify)
 *
 * XEdDSA verify = Ed25519 verify standar setelah:
 *   1. convertPublicKey: montgomery u → edwards y = (u-1)/(u+1)
 *   2. restore sign bit dari signature[63] ke pubkey
 *   3. hapus sign bit dari signature[63] (kembalikan S asli)
 * Pakai ed25519-dalek verify (R = S*B + h*A), bukan manual — dalek lebih
 * aman + sudah divalidasi. Nonce di verify memang standard (h = SHA512(R||A||m));
 * yang custom cuma di sisi sign.
 */
export declare function verify(publicKey: Uint8Array, msg: Uint8Array, signature: Uint8Array): boolean
